In [3]:
# !pip install nptyping
# !pip install beartype --index-url https://pypi.python.org/simple/

In [4]:
import numpy as np

In [5]:
# scalar
a : np.ndarray = np.array(1000)
display(f'object: {a}')
display(f'shape: {a.shape}')
display(f'size: {a.size}')
display(f'dimensions: {a.ndim}')
display(f'dtype: {a.dtype}')
display(f'type global: {type(a)}')
display(f'itemsize: {a.itemsize}') # representing the number of bytes for one element in the array

'object: 1000'

'shape: ()'

'size: 1'

'dimensions: 0'

'dtype: int32'

"type global: <class 'numpy.ndarray'>"

'itemsize: 4'

In [6]:
# vector 1-dim
a : np.ndarray = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
display(f'object: {a}')
display(f'shape: {a.shape}')
display(f'size: {a.size}')
display(f'dimensions: {a.ndim}')
display(f'dtype: {a.dtype}')
display(f'type global: {type(a)}')
display(f'itemsize: {a.itemsize}') # representing the number of bytes for one element in the array

'object: [ 1  2  3  4  5  6  7  8  9 10]'

'shape: (10,)'

'size: 10'

'dimensions: 1'

'dtype: int32'

"type global: <class 'numpy.ndarray'>"

'itemsize: 4'

In [7]:
# vector 2-dim
a : np.ndarray = np.array([[1, 2, 3], [4, 5, 6]])
display(f'object: {a}')
display(f'shape: {a.shape}')
display(f'size: {a.size}')
display(f'dimensions: {a.ndim}')
display(f'dtype: {a.dtype}')
display(f'type global: {type(a)}')
display(f'itemsize: {a.itemsize}') # representing the number of bytes for one element in the array

'object: [[1 2 3]\n [4 5 6]]'

'shape: (2, 3)'

'size: 6'

'dimensions: 2'

'dtype: int32'

"type global: <class 'numpy.ndarray'>"

'itemsize: 4'

In [8]:
# Numpy with NDArray typing
from nptyping import NDArray, Shape, UInt64
a : NDArray[Shape['10'], UInt64] = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
display(f'object: {a}')
display(f'shape: {a.shape}')
display(f'size: {a.size}')
display(f'dimensions: {a.ndim}')
display(f'dtype: {a.dtype}')
display(f'type global: {type(a)}')
display(f'itemsize: {a.itemsize}') # representing the number of bytes for one element in the array

'object: [ 1  2  3  4  5  6  7  8  9 10]'

'shape: (10,)'

'size: 10'

'dimensions: 1'

'dtype: int32'

"type global: <class 'numpy.ndarray'>"

'itemsize: 4'

In [9]:
# Numpy with NDArray typing
from nptyping import NDArray, Shape, UInt64
a : NDArray[Shape['10'], UInt64] = np.arange(1, 6)
display(f'object: {a}')
a += 5 # add 5 to each element
display(f'object: {a}')

'object: [1 2 3 4 5]'

'object: [ 6  7  8  9 10]'

In [10]:
# lst = [1, 2, 3, 4, 5]
# lst += 5 # error
lst = [i + 5 for i in lst]
print(lst)

NameError: name 'lst' is not defined

In [ ]:
%%time
a : NDArray[Shape['10'], UInt64] = np.arange(1, 1000000)
a += 5 

CPU times: total: 0 ns
Wall time: 1.94 ms


In [ ]:
%%time
from typing import List
lst: List[int] = list(range(1, 1000000))
lst = [i + 5 for i in lst]

CPU times: total: 78.1 ms
Wall time: 100 ms


In [ ]:
# numpy advance operation vs list
data : List[int] = list(range(1, 21))
display(data[5:11])
# data[5:11] = 100 # it will cause error only assign an iterable
# display(data)

[6, 7, 8, 9, 10, 11]

In [ ]:
data: NDArray[Shape['20'], UInt64] = np.arange(1, 21)
display(data[5:11])
data[5:11] = 100
display(data)

array([ 6,  7,  8,  9, 10, 11])

array([  1,   2,   3,   4,   5, 100, 100, 100, 100, 100, 100,  12,  13,
        14,  15,  16,  17,  18,  19,  20])

In [ ]:
from nptyping import NDArray, Shape, UInt64, Bool

# Creating the state_bank array with type UInt64
state_bank: NDArray[Shape['5'], UInt64] = np.arange(1, 6, dtype=np.uint64)

# Creating the conditions array with type Bool
conditions: NDArray[Shape['5'], Bool] = np.array([True, False, True, False, True], dtype=bool)

# Using display to show the filtered array
print(state_bank[conditions])  # Output: [1 3 5]


[1 3 5]


In [ ]:

# Creating the state_bank array with type UInt64
state_bank: NDArray[Shape['5'], UInt64] = np.arange(1, 6, dtype=np.uint64)

conditions = state_bank % 2 == 0

# Using display to show the filtered array
print(state_bank[conditions])  # Output: [1 3 5]


[2 4]


In [ ]:
# Install necessary packages (Run in terminal if not already installed)
# !pip install beartype numpy
from beartype import beartype
from beartype.typing import Union
from beartype.vale import Is
import numpy as np
from numpy.typing import NDArray
from numpy import uint64

# Define custom type constraints
UInt64 = uint64

# Function using beartype for type checking
@beartype
def create_state_bank() -> NDArray[UInt64]:
    # Array of shape (10,) and dtype uint64
    return np.arange(1, 11, dtype=UInt64)

@beartype
def create_ubl_bank() -> NDArray[UInt64]:
    # Array of shape (20,) and dtype uint64
    return np.random.randint(1, 100, 20, dtype=UInt64)

# Initialize arrays
state_bank: NDArray[UInt64] = create_state_bank()
ubl_bank: NDArray[UInt64] = create_ubl_bank()

# Display arrays
print("State Bank:")
print(state_bank)
print("UBL Bank:")
print(ubl_bank)


State Bank:
[ 1  2  3  4  5  6  7  8  9 10]
UBL Bank:
[24 28 46  3 32 69 71  7 71 75 73  2 32 98 54 69  1 47 96 83]


In [ ]:

state_bank = np.arange(1, 11, dtype=np.uint64)

ubl_bank = np.array([1, 3, 5, 7, 10])

display(f'State Bank: {state_bank}')

display(f'UBL Bank: {ubl_bank}')

print('state_bank[np.in1d(state_bank, ubl_bank)]')

display(state_bank[np.in1d(state_bank, ubl_bank)])


'State Bank: [ 1  2  3  4  5  6  7  8  9 10]'

'UBL Bank: [ 1  3  5  7 10]'

state_bank[np.in1d(state_bank, ubl_bank)]


array([ 1,  3,  5,  7, 10], dtype=uint64)

In [ ]:

state_bank = np.arange(1, 11, dtype=np.uint64)

ubl_bank = np.array([1, 3, 5, 7, 10])

display(f'State Bank: {state_bank}')

display(f'UBL Bank: {ubl_bank}')

print('np.intersect(state_bank, ubl_bank)')

display(np.intersect1d(state_bank, ubl_bank))


'State Bank: [ 1  2  3  4  5  6  7  8  9 10]'

'UBL Bank: [ 1  3  5  7 10]'

np.intersect(state_bank, ubl_bank)


array([ 1.,  3.,  5.,  7., 10.])

In [ ]:

state_bank = np.arange(1, 11, dtype=np.uint64)

ubl_bank = np.array([1, 3, 5, 7, 10])

display(f'State Bank: {state_bank}')

display(f'UBL Bank: {ubl_bank}')

print('np.intersect(state_bank, ubl_bank)')

display(np.where(ubl_bank % 2 == 0, 0,ubl_bank))


'State Bank: [ 1  2  3  4  5  6  7  8  9 10]'

'UBL Bank: [ 1  3  5  7 10]'

np.intersect(state_bank, ubl_bank)


array([1, 3, 5, 7, 0])

In [11]:
# Create numpy arrays
import numpy as np 
from typing import Any
a : NDArray[Shape['Size,Size'], Any] = np.array([[1, 2, 3], [4, 5, 6]])

b : NDArray[Shape['Size,Size'], Any] = np.array([['A', 'b', 'C'], [4, 5, 6]])

c : NDArray[Shape['Size,Size'], Any] = np.array([[1, 0], [4, 5]])

d : NDArray[Shape['*,*'], Any] = np.array([[1, 0, 1], [4, 5, 1]])

display(a)
display(b)
display(c)
display(d)

array([[1, 2, 3],
       [4, 5, 6]])

array([['A', 'b', 'C'],
       ['4', '5', '6']], dtype='<U11')

array([[1, 0],
       [4, 5]])

array([[1, 0, 1],
       [4, 5, 1]])

In [12]:
a : NDArray[Shape['Size,Size'], Any] = np.arange(1, 6)
b : NDArray[Shape['Size,Size'], Any] = np.arange(1, 18)
display(a)
display(b)

array([1, 2, 3, 4, 5])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17])

In [13]:
a : NDArray[Shape['Size,Size'], Any] = np.arange(3 * 3).reshape((3, 3))
b : NDArray[Shape['Size,Size'], Any] = np.arange(5 * 3).reshape((5, 3))
display(a)
display(b)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [14]:
a : NDArray[Shape['Size,Size'], Any] = np.arange(5 * 3 * 3).reshape((5, 3, 3))
b : NDArray[Shape['Size,Size'], Any] = np.arange(2 * 5 * 3).reshape((2, 5, 3))
display(a)
display(b)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]],

       [[27, 28, 29],
        [30, 31, 32],
        [33, 34, 35]],

       [[36, 37, 38],
        [39, 40, 41],
        [42, 43, 44]]])

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]],

       [[15, 16, 17],
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]]])

In [15]:
a[::,::,::]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]],

       [[27, 28, 29],
        [30, 31, 32],
        [33, 34, 35]],

       [[36, 37, 38],
        [39, 40, 41],
        [42, 43, 44]]])

In [16]:
a[2]

array([[18, 19, 20],
       [21, 22, 23],
       [24, 25, 26]])

In [17]:
a[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]],

       [[36, 37, 38],
        [39, 40, 41],
        [42, 43, 44]]])

In [18]:
a[2:4, :1, : ]

array([[[18, 19, 20]],

       [[27, 28, 29]]])

In [19]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [20]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [27]:
a = np.arange(1, 10).reshape((3,3))
np.ones_like(a)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [28]:
b : NDArray[Shape['Size,Size'], Any] = np.arange(2 * 5 * 3).reshape((2, 5, 3))
b

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]],

       [[15, 16, 17],
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]]])

In [31]:

b[0, [1], [0, 2]]

array([3, 5])

In [34]:
a = np.arange(1, 21)
print(f'max: {a.max()}')
print(f'min: {a.min()}')
print(f'mean: {a.mean()}')
print(f'argmax: {a.argmax()}')
print(f'argmin: {a.argmin()}')
print(f'std: {a.std()}')
print(f'sum: {a.sum()}')

max: 20
min: 1
mean: 10.5
argmax: 19
argmin: 0
std: 5.766281297335398
sum: 210


In [47]:
a = np.array([1, 2, np.nan, 3, 4,10, np.nan, 12])
np.where(np.isnan(a), np.nanmean(a), a)

array([ 1.        ,  2.        ,  5.33333333,  3.        ,  4.        ,
       10.        ,  5.33333333, 12.        ])